### ISSUE TITLE
platform -mqtt should be fall under its own key now: mqtt

### ISSUE THREAD

**Issue by meijer3** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#123]
```
sensor:
  - platform: mqtt
```
is old, and deprecated, the new way to go is.
```
mqtt:
  sensor:
```

https://www.home-assistant.io/integrations/sensor.mqtt/
![image](https://user-images.githubusercontent.com/45625341/198943607-d9221dd9-6474-4400-bbb7-94563cb0e740.png)

**Comment by MichielVanwelsenaere** [comment]
thanks for bringing this up. Will look into it.
