### ISSUE TITLE
MQTT switch 

### ISSUE THREAD

**Issue by meijer3** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#124]
Hi,

My WRITE_SWITCHES is like:
<pre>
FB_DO_SW_001(OUT=>DO_001 ,PRIO_HIGH:=FALSE,  PRIO_LOW:=FALSE,TOGGLE:=FB_DI_PB_001.SINGLE );
</pre>
I update MQTT with home assistant, to 
`Devices/PLC/House/In/DigitalOutputs/FB_DO_SW_001` : `FALSE` / `TRUE`.
but nothing is changing. I have two questions.
1. I saw in the other issue, that TOGGLE can be set to `FALSE`, but I want both an input pushbutton and overrule it with MQTT. I assumed this was possible, can you confirm that?
2. Do you have any clue why MQTT is not updating the callback function blocks. I am not good in debugging in e!Cockpit (yet... )

**Comment by MichielVanwelsenaere** [comment]
Could you provide a copy of your project?
Do you see MQTT hartbeat messages on the broker for the PLC?

**Comment by meijer3** [comment]
[HomeAutomation.Device.HomeAutomation.dc8b4b06-db0a-415d-9c9a-bbaa6953bc53.zip](https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/files/9907326/HomeAutomation.Device.HomeAutomation.dc8b4b06-db0a-415d-9c9a-bbaa6953bc53.zip)
MQTT is working. I can see the changes up to home assistant. 
![image](https://user-images.githubusercontent.com/45625341/199169655-44e885bf-6b09-4a1e-8d60-d44021f2b3c7.png)
![image](https://user-images.githubusercontent.com/45625341/199169951-40af0035-fb2f-463b-a5a5-7bdb8deee5fd.png)

**Comment by MichielVanwelsenaere** [comment]
I'm unable to open your project. I'm getting a 'could not open project error' when attempting..

> I want both an input pushbutton and overrule it with MQTT. I assumed this was possible, can you confirm that?

depends on what you call 'overrule', I have pushbuttons configured to output function blocks as well. If someone presses the pushbutton, it will toggle, if a MQTT message is received it will toggle as well. They work side by side.

I'm a bit confused to what is going on with your MQTT topics, looks like a mix of the old MQTT topic structure I factored out some time ago. Are you trying to replicate the update into your own project?

Either way, perhaps the following will clarify somethings for you:

1. publish topic(s): defined in 'PLC_PRG_MAIN' variables
2. hartbeat topic: defined in 'PLC_PRG_MQTT' variables
3. subscribe topic(s) defined in 'PLC_PRG_MQTT' -> 'MQTT_SUBSCRIBE':
![image](https://user-images.githubusercontent.com/6965657/199285858-b8c599c8-d035-4708-ac1a-7bc3e2f0ce10.png)
This is also where the topics are coupled to a 'collector' function block which in turn is then used in other function blocks.

Let me now if this helps.

**Comment by meijer3** [comment]
I can try it once more, a fresh 'save as'. If nothing works, I could share my screen. (also active on tweakers)
[src.zip](https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/files/9917404/src.zip)
I started off with your latest `.ecp` and did a 'device replacement' and added 8 DO/DI. Thats all I did.

The topic is like in your screenshot. Here is my screenshot, but online.
![image](https://user-images.githubusercontent.com/45625341/199423407-3b7b88b5-06a0-4e5c-91e2-adc7f212bde8.png)

And the online FB_OUTPUT_SWITCH_MQTT>PublishedReceived.
![image](https://user-images.githubusercontent.com/45625341/199424248-61e48372-955e-497c-bbfe-a9753b32e48f.png)

**Comment by MichielVanwelsenaere** [comment]
for certainty I just took a fresh copy as well and everything seems to be working perfectly;
![image](https://user-images.githubusercontent.com/6965657/199448015-f694dac0-057c-4548-9acb-ef21d4a2693d.png)

What I can see in your image is that the 'MQTTSubscribeTopic' starts with 'WAGO-PFC20...', this is part of the old naming and probably the issue here as well. 

Are you sure these are set correctily in your project:
![image](https://user-images.githubusercontent.com/6965657/199448609-aa2c0aaf-614b-4503-bb9a-8a7fa0ad31b9.png)
?

**Comment by meijer3** [comment]
I did a `cleanAll` and a new download and it started working again. Indeed I lost the 'WAGO-PFC20...'.
It is working like a charm now. Thank you so much for all the effort you put in this ( the whole repo! )
