### ISSUE TITLE
FB_RS485_EASTRON_SDM_POWER_MQTT: SDM120 support

### ISSUE THREAD

**Issue by meijer3** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#125]
The Eastron SDM220 and SDM630 are supported now. 
Can SDM120 support be added? I am happy to test.

**Comment by MichielVanwelsenaere** [comment]
I suppose this request is for 'FB_RS485_EASTRON_SDM_POWER_MQTT'?

**Comment by MichielVanwelsenaere** [comment]
I added support for the requested functionality in this branch;
https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/tree/feature/FB_RS485_EASTRON_SDM_POWER_MQTT-sdm120Support

You can update the function blocks in your project by using this procedure: [link](
https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/blob/feature/FB_RS485_EASTRON_SDM_POWER_MQTT-sdm120Support/docs/FAQ/Howto_updating_function_blocks.md)

Please let me know when you've tested the functionality.

small fyi; I don't get any notifications for thumbs up on comments, almost missed it.
