### ISSUE TITLE
AccessViolation in latest Master Branch

### ISSUE THREAD

**Issue by alegsan** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#141]
Hi Michiel,

after updating to the lastest master branch i get an access violation. It seems that the variable `pMqttPublishQueue` is empty. Any hint were the problem is?

<img width="1722" alt="access-violation" src="https://user-images.githubusercontent.com/42956589/218576726-f414c194-9e96-4f69-a96a-11e8f2c59eff.PNG">

<img width="1157" alt="access-violation-log" src="https://user-images.githubusercontent.com/42956589/218577092-5d5f3749-c4f1-4a30-b78d-949d9452c977.PNG">

**Comment by MichielVanwelsenaere** [comment]
Hi,

in 'MAIN_INIT' you should have the call below to initialize the device with the required variables (which you seem to be missing):
```
PLC_DEVICE.initPlcDevice(
	MqttDiscoveryPrefix := MqttVariables.MqttHADiscoveryPrefix,
	availabilityTopic := MqttVariables.MqttAvailabilityTopic,
	availabilityOnline := MqttVariables.MqttAvailabilityOnlinePayload,
	availabilityOffline := MqttVariables.MqttAvailabilityOfflinePayload,
	pMqttPublishQueue := ADR(MqttVariables.fbMqttPublishQueue)
);
```

Note that this call has to be executed before any other calls which concern MQTT Discovery.

Please check and revert :)

**Comment by alegsan** [comment]
> Hi,

Hi,

> 
> in 'MAIN_INIT' you should have the call below to initialize the device with the required variables (which you seem to be missing):
> 
> ```
> PLC_DEVICE.initPlcDevice(
> 	MqttDiscoveryPrefix := MqttVariables.MqttHADiscoveryPrefix,
> 	availabilityTopic := MqttVariables.MqttAvailabilityTopic,
> 	availabilityOnline := MqttVariables.MqttAvailabilityOnlinePayload,
> 	availabilityOffline := MqttVariables.MqttAvailabilityOfflinePayload,
> 	pMqttPublishQueue := ADR(MqttVariables.fbMqttPublishQueue)
> );

I have imported the whole project in a separated test project and reduced everything to only one pushbutton. Also the `initPlcDevice` function is called. But the access violation still occurs.

![main-init](https://user-images.githubusercontent.com/42956589/218704113-cbce53ce-0e30-4fa0-be7a-b774b4358f21.PNG)


Maybe anything else i'am doing wrong?

**Comment by MichielVanwelsenaere** [comment]
I don't think you're doing anything wrong. I was working on refactoring the 'InitPlcDevice' method and looking at the existing logic I think I see where it can go wrong.

I created PR #142, could you take a look at the source branch and use the openXml to update everything in your 'MqttDiscovery' folder? You'll need to adopt the call to 'InitPlcDevice' as well as it now requires an additional parameter which you can find the MqttVariables.

Your the first one to try the MqttDiscovery functionality in Codesys, let me know how the 'device' section of the mqtt discovery message looks like. Ideally it matches what we have in éCockpit.

**Comment by alegsan** [comment]
> I created PR #142, could you take a look at the source branch and use the openXml to update everything in your 'MqttDiscovery' folder? You'll need to adopt the call to 'InitPlcDevice' as well as it now requires an additional parameter which you can find the MqttVariables.

Ok that looks good. No access violation anymore. Thanks Michiel :thumbsup:


> Your the first one to try the MqttDiscovery functionality in Codesys, let me know how the 'device' section of the mqtt discovery message looks like. Ideally it matches what we have in éCockpit.

Here is the mqtt discovery message:
```
{"name":"Button number 001","obj_id":"PFC100_FB_DI_PB_001","uniq_id":"PFC100_FB_DI_PB_001","avty":[{"topic":"Devices/PLC/House/availability"},{"topic":"Devices/PLC/House/availability"}],"avty_mode":"all","pl_avail":"online","pl_not_avail":"offline","dev":{"name":"PFC100","cu":"https://192.168.178.184","ids":"0030DEAABBCC","mf":"WAGO","mdl":"WAGO 750-8102 PFC100 CS 2ETH RS","sw":"3.5.17.30","hw":"DT#2023-02-14-21:50:42"},"qos":2,"meta":null,"stat_t":"Devices/PLC/House/Out/DigitalInputs/Pushbuttons/FB_DI_PB_001","exp_aft":2}
```

Looks also good in homeassistant :thumbsup:
