### ISSUE TITLE
MQTT discovery: Support 'VALVE' entity 

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#154]
HomeAssistant recently introducted the 'Valve' entity together with a MQTT integration;
https://www.home-assistant.io/integrations/valve.mqtt/

Update the MQTT discovery logic so it's supported.

**Comment by lboorman** [comment]
Hi @MichielVanwelsenaere did you make progress on this?

Thanks

**Comment by MichielVanwelsenaere** [comment]
I did, just didn't manage to find the time to propogate this back to the project.
Will look into this, thanks for the reminder.
