### ISSUE TITLE
MQTT connection status

### ISSUE THREAD

**Issue by YorickErnst** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#33]
Hi Michiel,

I've started working with your latest release, and would like to make a split scenario where one instruction is executed if no MQTT connection is made and another instruction is done if there is an MQTT connection.

At the moment all messages end up fine in my MQTT broker but the MQTT_CONNECTED value in MQTTInfo remains FALSE.

**Comment by MichielVanwelsenaere** [comment]
Hi,

The MQTT_CONNECTED in MQTTInfo becomes high for one PLC cycle when there's an initial connector and when there's a reconnect to the MQTT broker.

Nevertheless, it does make sense to have a boolean indicating the connection status to the broker for purposes like you are indicating. I'll check what I can find but might need to redirect that question to Stefan (MQTT lib developer).

**Comment by MichielVanwelsenaere** [comment]
Just gave this a look, the boolean below under the MQTTClient object seems what you need:
![image](https://user-images.githubusercontent.com/6965657/70122553-24a30380-1671-11ea-9c83-145767ec3700.png)

let me know if that answers your question.

**Comment by YorickErnst** [comment]
Perfect, that's indeed what I need :)
