### ISSUE TITLE
Assign the PLC serial port to the PLC runtime

### ISSUE THREAD

**Issue by ntphx** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#58]
The screenshot under the `Assign the PLC serial port to the PLC runtime` header in file `UsingModbusRTU_éCOCKPIT.md` has the Service Interface tab open. Should this be the Serial Interface tab instead?

Here's a screenshot of the Serial Interface tab

<img width="764" alt="Screenshot 2020-03-25 at 13 18 53" src="https://user-images.githubusercontent.com/31240576/77535843-9ced3900-6e9b-11ea-9f11-f3a4a012b9b7.png">

**Comment by MichielVanwelsenaere** [comment]
you're totally right, thanks for letting me know! I'll adjust it ASAP!
