### ISSUE TITLE
Make FB_OUTPUT_DIMMER_MQTT comaptible with floating point value subscription

### ISSUE THREAD

**Issue by primsam** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#65]
Hello,

I had a lot of headaches lately with a subscription coming from Openhab.
In openhab the default Dimmer Pub/Sub for MQTT send´s a Real value eg. 70.22 and to fix that it´s a lot of trouble for one that is not so familiar with Java/Json like me XD.
But there is a easy fix for that in the FB_OUTPUT_DIMMER_MQTT/PublishReceived block.
Simple change `ELSIF OSCAT_BASIC.IS_NUM(str:= Data.PayloadString^)`
to `ELSIF OSCAT_BASIC.IS_CC(str:= Data.PayloadString^,cmp:='0123456789.')`

Original:
`//first check if Mqtt is initialized, otherwise do nothing
IF NOT(InitMqttDone) THEN
	//mark the interface call from the collector as done
	PublishReceived := TRUE;
//check if the packet is for this FB
ELSIF CommonTypesAndFunctions.StrEquals(str1:= ADR(MQTTSubscribeTopic), str2:= Data.TopicOut) THEN
	//mark the interface call from the collector as done
	PublishReceived := TRUE;
	//now process the data
	IF CommonTypesAndFunctions.StrEquals(str1:= Data.PayloadString, str2:= ADR('TRUE')) THEN
		MqttHighRequest := TRUE;
	ELSIF CommonTypesAndFunctions.StrEquals(str1:= Data.PayloadString, str2:= ADR('FALSE')) THEN
		MqttLowRequest := TRUE;
	ELSIF OSCAT_BASIC.IS_NUM(str:= Data.PayloadString^) AND THIS^.PRIO_HIGH = FALSE THEN
		THIS^.OUT:=STRING_TO_BYTE(Data.PayloadString^);
	END_IF
END_IF `

And the new one :

`//first check if Mqtt is initialized, otherwise do nothing
IF NOT(InitMqttDone) THEN
	//mark the interface call from the collector as done
	PublishReceived := TRUE;
//check if the packet is for this FB
ELSIF CommonTypesAndFunctions.StrEquals(str1:= ADR(MQTTSubscribeTopic), str2:= Data.TopicOut) THEN
	//mark the interface call from the collector as done
	PublishReceived := TRUE;
	//now process the data
	IF CommonTypesAndFunctions.StrEquals(str1:= Data.PayloadString, str2:= ADR('TRUE')) THEN
		MqttHighRequest := TRUE;
	ELSIF CommonTypesAndFunctions.StrEquals(str1:= Data.PayloadString, str2:= ADR('FALSE')) THEN
		MqttLowRequest := TRUE;
	ELSIF OSCAT_BASIC.IS_CC(str:= Data.PayloadString^,cmp:='0123456789.') AND THIS^.PRIO_HIGH = FALSE THEN
		THIS^.OUT:=STRING_TO_BYTE(Data.PayloadString^);
	END_IF
END_IF `

**Comment by MichielVanwelsenaere** [comment]
Hi,

It makes indeed sense to make the subscription also handle float values and just round to the nearest int value.

I'll doublecheck and test your codesample and add this to the project. Thanks for your feedback!
