### ISSUE TITLE
Codesys V3.5 SP16  Oscat library (basic) 

### ISSUE THREAD

**Issue by thomkedc** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#76]
Hi,

The Basic library under 'BUILDING (OSCAT)  needs to be updated.
the updates that needs to be done are minor  but since i don't have the source from the building library (only the BASIC can i find on the OSCAT website)  I can add an new BASIC library, but then it's not included into the 'Building' Library'

See image below: (so the circled one is the library without any errors, this once should replace the basic library in the building folder )
![LibaryIssue](https://user-images.githubusercontent.com/14280323/99068442-d39fcd00-25ac-11eb-905e-5e9286a84414.JPG)

**Comment by MichielVanwelsenaere** [comment]
hmmm, that's a painful dependency problem..
what Codesys version are you using? this seems tied to a newer codesys version that introduces a new datatype 'LDT'.

My suggestion: try to get your hands on an older Codesys version to get you unblocked 

In the meantime we'll fire up a project to have our own library that contains the most important functionalities to get rid of any dependency problems (now and in the future).

**Comment by drled** [comment]
I'm also using codesys V3.5 SP16 and cannot download the missing libraries needed for MQTT.
I'm not sure wether this is related to the same dependency problem?

![library_download_fail](https://user-images.githubusercontent.com/9850136/99938992-5c66f780-2d69-11eb-8ced-c7f9dd85b527.JPG)

**Comment by MichielVanwelsenaere** [comment]
are all those library issues related to the MQTT library?

**Comment by drled** [comment]
Thanks for your quick feedback.
I have errors in the following libs:
CommonTypsFunctions (Stefan Dreyer)
OSCAT Network(ie. SysFile23, SysSocket23)
SD_MQTT(CAA_File,CmpCrypto,...)

![libs_issue_v2](https://user-images.githubusercontent.com/9850136/99941273-09437380-2d6e-11eb-8abd-2984cd776b0e.JPG)
![missing_v3_codesys](https://user-images.githubusercontent.com/9850136/99941335-2415e800-2d6e-11eb-8420-ddfc777f632f.JPG)

**Comment by MichielVanwelsenaere** [comment]
CommonTypsFunctions (Stefan Dreyer) -> could you open an issue on his repo for these? feel free to link/mention it over here as well. Time to get these dependency problems sorted out 😄 
OSCAT Network(ie. SysFile23, SysSocket23) -> the two you are describing are normally under the 'libraries' folder in the solution, could you import them?
SD_MQTT(CAA_File,CmpCrypto,...) -> thanks for the complete list, I'll check if I can find these myself and create a library repo with everything in it

For all clarity: there's work ongoing to limit the amount of library dependencies this project has but it's only just getting started.

**Comment by MichielVanwelsenaere** [comment]
@drled , do you still have some dependency problems? 
Otherwise, you can leverage this repo to get your missing files:
https://github.com/OpenHomeToolkit/CoDeSys3.LibraryRepo

let me know if that helps.

**Comment by drled** [comment]
I was able to resolve most of the issues.

Now what's left is the same issue that was mentioned by @thomkedc. The LDT output tag in the RTC_2 functionblock of the Oscat basic lib is being recognized as a datatype.
![fault_rtc2lib](https://user-images.githubusercontent.com/9850136/100480268-173c2000-30f1-11eb-85cb-b09e88c84071.JPG)

**Comment by MichielVanwelsenaere** [comment]
That was to be expected unfortunattely.
Work has started to extract & refactor the required piece of the OSCAT libs yet it's going to take some time..

Same remark as for Thomke, can you download an older version of Codesys to get you unblocked?

**Comment by drled** [comment]
I installed codesys V3.5 SP15 and got it up and running without any dependency issue. Thank you!

**Comment by rmeekers** [comment]
any updates on this issue?

**Comment by MichielVanwelsenaere** [comment]
> 
> 
> any updates on this issue?

actually, yes! 
I asked a bit around and normally Codesys SP16 should come with an adjusted version of the OSCAT libs avoiding the compilation problem above. Haven't found time to verify yet however.

Feel free to look for them of you've got SP16 or higher installed.

**Comment by MichielVanwelsenaere** [comment]
you can find the updated libs here:
https://store.codesys.com/catalogsearch/result/?q=OSCAT

I'll incorporate them in the project as the default when I have a moment.
