### ISSUE TITLE
Errors in project

### ISSUE THREAD

**Issue by Dorme** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#84]
I've been following the installation video's for a few times now, but I still keep getting errors in my project.
I'm using a Wago PFC200 with Codesys v3.5 SP16 Patch 3.

![image](https://user-images.githubusercontent.com/3600370/110327041-be4a2500-8019-11eb-8c18-996870ab8fcb.png)

![image](https://user-images.githubusercontent.com/3600370/110327056-c3a76f80-8019-11eb-9d2a-996b7cc4529a.png)

There are no errors in the Library Manager:

![image](https://user-images.githubusercontent.com/3600370/110327109-d621a900-8019-11eb-86ac-4998add38635.png)

Also Codesys Control for PFC200 is correctly installed:

![image](https://user-images.githubusercontent.com/3600370/110327151-e6398880-8019-11eb-843d-07c334fb168d.png)

Anyone can point me towards the correct direction to solve this issue?

**Comment by MichielVanwelsenaere** [comment]
Hi Dorme,

let's start with trying to get the basics to work. 
- Let's start with disabling the RS485 task (remove it from the taskconfiguration):
![image](https://user-images.githubusercontent.com/6965657/110328446-a96e9100-801b-11eb-8dee-5850a326c8a6.png)

- could you show me the errors in 'PLC_PRG_MAIN'? that's the main PRG that is most straight forward so I'd like to start with getting that one to work.

In addition; some problems have been reported with this project and compatibility with Codesys v3.5 SP16 (#76). If this is costing you to much time effort, perhaps also consider a downgrade until I find some time to check the compatibility problems with SP16.

**Comment by Dorme** [comment]
When switching to Codesys v3.5 SP15, I manged to get more stuff working. When leaving out the RS485 task, I can build and upload the project to the PLC. When I enable the RS485 task, I get theses errors:

![image](https://user-images.githubusercontent.com/3600370/110372805-06d00580-804f-11eb-9801-9f3ba5507a4f.png)

**Comment by MichielVanwelsenaere** [comment]
Great! For RS485 in Codesys 3S you need to do some setup. These docs should help you out:
https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/blob/master/docs/RS485/UsingModbusRTU_CODESYS3S.md

**Comment by Dorme** [comment]
If I'm not using the RS485 port on the PLC, I assume I can safely delete this task?

**Comment by MichielVanwelsenaere** [comment]
indeed. It's only there as a 'boilerplate' for you. My FYI; it comes in mighty handy for reading out energy meters and all kinds of sensors in a reliable way. Naturally all setups are unique, just something to keep in mind.

**Comment by Dorme** [comment]
Thanks for the clarification. I'll keep it in mind. Swithing to Codesys v3.5 SP15 did the trick.
