### ISSUE TITLE
RS485 pin-out for PFC200 is incorrect

### ISSUE THREAD

**Issue by sf-prime** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#90]
Connection example for PFC200 is not correct. [The documentation](https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/blob/master/docs/FunctionBlocks/FB_RS485_EASTRON_SDM220_MQTT.md#wago-pfc-wiring-diagram) mentions that RS-485 signal A should be connected to pin 3 and signal B to pin 9. According to the Wago PFC200 user manual, the latter should be pin 8:

![WAGO PFC200 user manual extract](https://user-images.githubusercontent.com/60754506/121424776-01e26100-c972-11eb-8ef3-7d7d5cc31e96.png)

**Comment by MichielVanwelsenaere** [comment]
absolutely correct! not sure what happened there. thanks for reporting
