### ISSUE TITLE
Question: WRITE_SWITCHES optional toggle

### ISSUE THREAD

**Issue by rmeekers** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#92]
I (ab?)use the WRITE_SWITCHES just to interact with a DO via MQTT and therefore I don't need a toggle. Is there a proper way to do it instead of assigning non existing contacts to it?

<img width="422" alt="image" src="https://user-images.githubusercontent.com/5755308/122462766-4646b000-cfb5-11eb-84bd-5d8b3865db00.png">

**Comment by MichielVanwelsenaere** [comment]
I would think that just using 'FALSE' for Toggle should do the trick?

**Comment by rmeekers** [comment]
Works fine. Thanks
